{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cd-collector.serviceAccountName" . }}
  labels:
    {{- include "cd-collector.labels" . | nindent 4 }}
{{- end }}
